# Generated by Django 5.1.1 on 2024-09-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Lecture',
        ),
    ]
